version: '3.8'
services:
  dynamodb-local:
    command: '-jar DynamoDBLocal.jar -sharedDb -dbPath ./data'
    image: 'amazon/dynamodb-local:latest'
    container_name: dynamodb-local
    ports:
      - '8000:8000'
    volumes:
      - './docker/dynamodb:/home/dynamodblocal/data'
    working_dir: /home/dynamodblocal
  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=dynamodb
    ports:
      - '4566:4566' # Port for DynamoDB
    volumes:
      - '${TMPDIR:-/tmp}/localstack:/tmp/localstack'
  my_service:
    environment:
      - DYNAMODB_ENDPOINT_LOCAL=http://dynamodb-local:8000
      - DYNAMODB_ENDPOINT_LOCAL_STACK=http://localstack:4566
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - '8081:8081'